### ISSUE TITLE
spec issue

### ISSUE THREAD

**Issue by amakhrov** [gartz/ObjectEventTarget#3]
https://github.com/gartz/ObjectEventTarget/blob/master/test/specs/ObjectEventTarget.js#L174
this doesn't seem to really test that `callbacks.third` was ever executed.

**Comment by gartz** [comment]
It's executing the third, but, yeah the test can be improved.

**Comment by amakhrov** [comment]
If it's not executed due to a bug, the test doesn't catch that.

**Comment by gartz** [comment]
If the second callback was executed the order result in the end would be 4 and not 3, because there is a order++

In this case it's removing the callback and executing the third callback correctly, but the test wasn't covering if the third callback was executed as you said, it only ensure that the second wasn't so I fixed it using a scope flag.

Fix commit: https://github.com/gartz/ObjectEventTarget/commit/6695e93ed52d355f54d11a3c830b33890bfa6c40
Thanks. :)
